### ISSUE TITLE
Issues with build.gradle

### ISSUE THREAD

**Issue by MartinPavlik** [witPranav/react-native-android-wake-screen#1]
Hi, 

I found an issue while trying to build a RN project with this package installed.

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/home/martin/work/app/node_modules/react-native-android-wake-screen/android/build.gradle' line: 98

* What went wrong:
A problem occurred configuring project ':react-native-android-wake-screen'.
> No such property: username for class: java.lang.String

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

The issue seems that the afterEvaluate hook in `build.gradle` is called even when the "host" app is build, not only when this package is published. I forked this repo and remove the afterEvaluate hook, shall we do the same here?

Thanks,

Martin

**Comment by witPranav** [comment]
Hello there. Sorry I was unable to look into this issue earlier. There seems to be an issue with gradle upgrades bricking this plugin. I'll look into it if I get time later.
Edit: For now, I have merged your commit. Thank you.
